apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-server-conf
  labels:
    name: elasticsearch-server-conf
  namespace: logging
data:
  elasticsearch.yml: |-
    filebeat.inputs:
    - type: filestream
      id: system-log-id
      paths:
        - /var/log/*
    - type: filestream
      id: kubernetes-log-id
      paths:
        - /var/log/kubernetes/*.log
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      username: "elastic"
      password: "1"