apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-server-conf
  labels:
    name: elasticsearch-server-conf
  namespace: monitoring
data:
  elasticsearch.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      username: "elastic"
      password: "1"
