apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-server-conf
  labels:
    name: kibana-server-conf
  namespace: logging
data:
  kibana.yml: |-
    server.name: kibana
    server.host: 0.0.0.0
    elasticsearch.hosts: [ http://elasticsearch:9200 ]
    
    monitoring.ui.container.elasticsearch.enabled: true
    monitoring.ui.container.logstash.enabled: true

    ## X-Pack security credentials
    #
    elasticsearch.username: kibana_system
    #elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
    elasticsearch.password: 1