apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.17.24
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: kibana-config-volume
              mountPath: /usr/share/kibana/config/
            - name: kibana-storage-volume
              mountPath: /usr/share/kibana/data

      volumes:
        - name: kibana-config-volume
          configMap:
            defaultMode: 420
            name: kibana-server-conf
        - name: kibana-storage-volume
          persistentVolumeClaim:
            claimName: elk-pvc
