apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.24
          env:
          - name: discovery.type
            value: single-node
          - name: ELASTIC_PASSWORD
            value: "1"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elasticsearch-config-volume
              mountPath: /etc/elasticsearch/
            - name: elasticsearch-storage-volume
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-config-volume
          configMap:
            defaultMode: 420
            name: elasticsearch-server-conf
        - name: elasticsearch-storage-volume
          emptyDir: {}
